## Importing the libraries

In [16]:
import pandas as pd
import numpy as np

## Reading the dataset

In [17]:
data = pd.read_csv(r'..\data\smartphone.csv')

In [18]:
data.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9

## Extracting basic data information

In [19]:
data.isnull().sum()

User_ID                      0
Age                          0
Gender                       0
Occupation                   0
Device_Type                  0
Daily_Phone_Hours            0
Social_Media_Hours           0
Work_Productivity_Score      0
Sleep_Hours                  0
Stress_Level                 0
App_Usage_Count              0
Caffeine_Intake_Cups         0
Weekend_Screen_Time_Hours    0
dtype: int64

In [20]:
data.dtypes

User_ID                       object
Age                            int64
Gender                        object
Occupation                    object
Device_Type                   object
Daily_Phone_Hours            float64
Social_Media_Hours           float64
Work_Productivity_Score        int64
Sleep_Hours                  float64
Stress_Level                   int64
App_Usage_Count                int64
Caffeine_Intake_Cups           int64
Weekend_Screen_Time_Hours    float64
dtype: object

In [21]:
data.shape

(50000, 13)

In [22]:
data.describe(include='all')

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
count,50000,50000.000000,50000,50000,50000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000
unique,50000,NaN,3,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,U1,NaN,Male,Professional,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,16708,12629,25080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,39.034960,NaN,NaN,NaN,6.509116,4.267250,5.503760,6.497744,5.504500,32.43898,3.004580,8.006844
std,NaN,12.414877,NaN,NaN,NaN,3.170903,2.164743,2.874806,1.449551,2.871095,16.12151,1.996657,3.461300
min,NaN,18.000000,NaN,NaN,NaN,1.000000,0.500000,1.000000,4.000000,1.000000,5.00000,0.000000,2.000000
25%,NaN,28.000000,NaN,NaN,NaN,3.800000,2.400000,3.000000,5.200000,3.000000,18.00000,1.000000,5.000000
50%,NaN,39.000000,NaN,NaN,NaN,6.500000,4.300000,5.500000,6.500000,6.000000,32.00000,3.000000,8.000000
75%,NaN,50.000000,NaN,NaN,NaN,9.200000,6.100000,8.000000,7.800000,8.000000,46.00000,5.000000,11.000000
max,NaN,60.000000,NaN,NaN,NaN,12.000000,8.000000,10.000000,9.000000,10.000000,60.00000,6.000000,14.000000

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    50000 non-null  object
 1   Age                        50000 non-null  int64
 2   Gender                     50000 non-null  object
 3   Occupation                 50000 non-null  object
 4   Device_Type                50000 non-null  object
 5   Daily_Phone_Hours          50000 non-null  float64
 6   Social_Media_Hours         50000 non-null  float64
 7   Work_Productivity_Score    50000 non-null  int64
 8   Sleep_Hours                50000 non-null  float64
 9   Stress_Level               50000 non-null  int64
 10  App_Usage_Count            50000 non-null  int64
 11  Caffeine_Intake_Cups       50000 non-null  int64
 12  Weekend_Screen_Time_Hours  50000 non-null  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 5.0+ MB

## Making Age groups

In [24]:
def age_group(age):
    if 18 <= age <= 28:
        return "18-28"
    elif 29 <= age <= 39:
        return "29-39"
    elif 40 <= age <= 50:
        return "40-50"
    else:
        return "51-60"

data['Age_Group'] = data['Age'].apply(age_group)

In [25]:
data.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Age_Group
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7,51-60
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1,18-28
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3,18-28
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8,29-39
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9,29-39

## Grouping App Counts

In [26]:
def app_usage_group(count):
    if 1 <= count <= 10:
        return "Light (1-10)"
    elif 11 <= count <= 20:
        return "Moderate (11-20)"
    elif 21 <= count <= 35:
        return "High (21-35)"
    else:
        return "Heavy (36-50)"

data['App_Usage_Count_Group'] = data['App_Usage_Count'].apply(app_usage_group)

In [27]:
data.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Age_Group,App_Usage_Count_Group
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7,51-60,Heavy (36-50)
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1,18-28,Heavy (36-50)
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3,18-28,Moderate (11-20)
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8,29-39,Heavy (36-50)
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9,29-39,Heavy (36-50)

## Saving the data

In [28]:
data.to_csv(r'..\data\smartphone.csv', index=False)